/**
 * SENZO MD — Curated local quotes collection
 * Zero-API, lifetime working. Mixed: motivation, islamic, urdu, deep.
 */
const QUOTES = [
  { text: "Zindagi mein kabhi ruko mat, chahe kuch bhi ho jaye.", author: "Senzo MD" },
  { text: "Sakoon sirf us waqt milta hai jab dil Allah ki yaad mein hota hai.", author: "Islamic" },
  { text: "Mehnat kabhi bekar nahi jati, bas waqt le leti hai.", author: "Motivation" },
  { text: "Aaj ka dard kal ki taqat banega.", author: "Motivation" },
  { text: "Namaz chhoro mat, chahe duniya kuch bhi kahe.", author: "Islamic" },
  { text: "Khush rahein ke Khuda aapko bhi khush rakhe.", author: "Dua" },
  { text: "Waqt sab ko deta hai, lekin sab waqt ki qadar nahi karte.", author: "Deep" },
  { text: "Mushkil waqt zindagi ka sabse bada teacher hota hai.", author: "Deep" },
  { text: "Sabr ka phal hamesha meetha hota hai.", author: "Islamic" },
  { text: "Jab tak mehnat karte ho, tab tak nahi haarte.", author: "Motivation" },
  { text: "Qismat likhni ho toh pehle Allah ki khush kar lo.", author: "Islamic" },
  { text: "Akela pan bhi ek taqat hai, agar sahi jagah use karo.", author: "Deep" },
  { text: "Umeed ka daman mat chhoro, subah zaroor hoti hai.", author: "Motivation" },
  { text: "Jo chhota samajhte ho usi se badi jeet aati hai.", author: "Deep" },
  { text: "Alhamdulillah hamesha, har haal mein.", author: "Islamic" },
  { text: "Apni value khud tay karo, log nahi.", author: "Confidence" },
  { text: "Dua ka koi waqt nahi hota, bas dil saaf hona chahiye.", author: "Islamic" },
  { text: "Log badlenge, waqt badlega, tum apna character mat badlo.", author: "Deep" },
  { text: "Har din nayi shuruat ka naam hai.", author: "Motivation" },
  { text: "Zubaan sambhal ke use karo, lafz dil tod dete hain.", author: "Deep" },
  { text: "Sach bolo, chahe kadwa lage.", author: "Wisdom" },
  { text: "Muskurao, tumhari muskurahat kisi ki dua hai.", author: "Heart" },
  { text: "Allah se maango, Woh de kar kabhi thakta nahi.", author: "Islamic" },
  { text: "Apne goals par kaam karo, logon ki baaton par nahi.", author: "Motivation" },
  { text: "Rishte wahi ache hain jahan respect ho.", author: "Deep" },
  { text: "Waqt guzar jayega, bas tum sahi raaste par raho.", author: "Wisdom" },
  { text: "Fajr ki namaz zindagi ki barakat hai.", author: "Islamic" },
  { text: "Khamoshi bhi ek jawab hai.", author: "Deep" },
  { text: "Jeet uski hoti hai jo himmat nahi chhorta.", author: "Motivation" },
  { text: "Maafi maangne se insan chhota nahi hota.", author: "Wisdom" },
  { text: "Acha waqt zaroor aata hai, bas intezaar ki taqat chahiye.", author: "Hope" },
  { text: "Quran padho, dil ko sukoon milega.", author: "Islamic" },
  { text: "Koshish karne walon ki kabhi haar nahi hoti.", author: "Motivation" },
  { text: "Neki chhupao, badnaam ho jao.", author: "Islamic" },
  { text: "Jo mila uska shukr karo, aur zyada milega.", author: "Islamic" },
  { text: "Sapne wo nahi jo neend mein aayein, wo hain jo neend nahi aane dete.", author: "Motivation" },
  { text: "Dost kam rakho, lekin sacche rakho.", author: "Deep" },
  { text: "Har musibat ke baad aasani hai.", author: "Quran 94:6" },
  { text: "Apne aap par bharosa rakho, Allah tumhara saath hai.", author: "Faith" },
  { text: "Bol kam socho zyada — yehi asal aqalmandi hai.", author: "Wisdom" },
  { text: "Waqt ki qadar karo, waqt tumhari qadar karega.", author: "Deep" },
  { text: "Tawakkul rakho, natija Allah par chhoro.", author: "Islamic" },
  { text: "Gusse mein faisla mat lo, phir pachhtana padta hai.", author: "Wisdom" },
  { text: "Mehnat + sabr = manzil.", author: "Motivation" },
  { text: "Aankhon ki sharm haya imaan ki nishani hai.", author: "Islamic" },
  { text: "Jitna aasan lagta hai, utna mushkil hota hai — isliye try karo.", author: "Deep" },
  { text: "Allah sab se behtar plan karta hai.", author: "Faith" },
  { text: "Apni kahani khud likho, logon ki nazar mein nahi.", author: "Confidence" },
  { text: "Roz thora sa behtar bano, bus.", author: "Motivation" },
  { text: "Waldain ki dua se zyada taqatwar cheez kuch nahi.", author: "Islamic" },
];

module.exports = QUOTES;
